[divisions]
    open = {name ="Open",min=0,max=999}
	masters40_49 = {name="Masters 40-49", min=40, max=49}
	masters50_59 = {name="Masters 50-59", min=50, max=59}
	masters60_69 = {name="Masters 60-69", min=60, max=69}
	masters70_79 = {name="Masters 70-79", min=70, max=79}

    disabled = {name ="Disabled",min=0,max=999}
    master1 = {name ="Masters 1",min=40,max=49}
    master2 = {name ="Masters 2",min=50,max=59}


[weightclasses.M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","110+","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
	2102 = ["ExemptWeightClassConsistency"] # Non-standard classes.
