[options]
    require_manual_disambiguation = true

[divisions]
    open = {name = "Open", min = 0, max = 999}
    sub_juniors = {name = "Sub-Juniors", min = 14, max = 19}
    juniors_20_23 = {name = "Juniors", min = 14, max = 23}

    masters_40_49 = {name = "Masters 1", min = 39.5, max = 49}
    masters_50_59 = {name = "Masters 2", min = 50, max = 59}
    masters_60_69 = {name = "Masters 3", min = 60, max = 69}
    masters_70_79 = {name = "Masters 4", min = 70, max = 999}

    masters = {name = "Masters", min = 39.5, max = 999}

[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
    9901 = ["ExemptWeightClassConsistency", "ExemptDivision"] # Extra weightclasses, fewer age divisions
    0001 = ["ExemptWeightClassConsistency"]
    0201 = ["ExemptWeightClassConsistency"] # Extra weightclasses
    0301 = ["ExemptWeightClassConsistency"] # Extra weightclasses
    0501 = ["ExemptWeightClassConsistency"] # Extra weightclasses
    1501 = ["ExemptWeightClassConsistency"]