# Configuration for WUAP.

[rulesets.default]
    ruleset = ["CombineRawAndWraps", "CombineSingleAndMulti"]
    date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    # Official WUAP divisions
    o = {name ="Open",min=0,max=999}
    j = {name ="Junior (20-23)",min=20,max=23}
    t = {name ="Teens (16-19)",min=16,max=19}
    m_40_49 = {name = "Master I (40-49)", min = 40, max = 49}
    m_50_59 = {name = "Master II (50-59)", min = 50, max = 59}
    m_60_69 = {name = "Masters III (60-69)", min = 60, max = 69}
    m_70_79 = {name = "Masters IV (70-79)", min = 70, max = 79}
    m_80_89 = {name = "Masters V (80-89)", min = 80, max = 89}

    # Old WUAP divisions, until 2022
    t1 = {name ="T1",min=13,max=15}
    t2 = {name ="T2",min=16,max=17}
    t3 = {name ="T3",min=18,max=19}
    m1 = {name ="M1",min=40,max=44}
    m2 = {name ="M2",min=45,max=49}
    m3 = {name ="M3",min=50,max=54}
    m4 = {name ="M4",min=55,max=59}
    m5 = {name ="M5",min=60,max=64}
    m6 = {name ="M6",min=65,max=69}
    m7 = {name ="M7",min=70,max=74}
    m8 = {name ="M8",min=75,max=79}
    m9 = {name ="M9",min=80,max=999}
    sm = {name ="SM",min=33,max=39}

    # Paralympics.
    para = {name="Para", min=0, max=999}

    # Not real divisions, but have been used on occasion
    m10 = {name ="M10",min=80,max=84}
    m11 = {name ="M11",min=85,max=89}

[weightclasses.old_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "2022-12-31"]
    sex = "M"

[weightclasses.default_M]
    classes = ["67.5","82.5","95","110","125","125+"]
    date_range = ["2023-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.old_F]
    classes = ["48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "2022-12-31"]
    sex = "F"

[weightclasses.default_F]
    classes = ["52","60","67.5","82.5","82.5+"]
    date_range = ["2023-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
    2401 = ["ExemptDivision"] # 15 year old competed in Teen (16-19) division