# Configuration for World Para Powerlifting.

[options]
    require_manual_disambiguation = true

[rulesets.default]
	ruleset = ["FourthAttemptsMayLower"]
	date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    open = {name="Open", min=0, max=999, equipment="Raw"}
    juniors = {name="Juniors", min=0, max=22.5, equipment="Raw"}
    groupa = {name="Group A", min=0, max=999, equipment="Raw"}
    groupb = {name="Group B", min=0, max=999, equipment="Raw"}
    groupc = {name="Group C", min=0, max=999, equipment="Raw"}
    lw = {name="Lightweight", min=0, max=999, equipment="Raw"}
    hw = {name="Heavyweight", min=0, max=999, equipment="Raw"}

[weightclasses.default_M]
    classes = ["49","54","59","65","72","80","88","97","107","107+"]
    date_range = ["2013-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["41","45","50","55","61","67","73","79","86","86+"]
    date_range = ["2013-01-01","9999-01-01"]
    sex = "F"

[weightclasses.old_M]
    classes = ["48","52","56","60","67.5","75","82.5","90","100","100+"]
    date_range = ["0000-01-01","2012-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["40","44","48","52","56","60","67.5","75","82.5","82.5+"]
    date_range = ["0000-01-01","2012-12-31"]
    sex = "F"

[exemptions]
    8401 = ["ExemptWeightClassConsistency"]
    1908 = ["ExemptWeightClassConsistency"] # Used old weightclasses.
