[options]
    require_manual_disambiguation = true


[divisions]
    open = {name = "SNR", min = 0, max = 999}
    teen_13_19 = {name = "SJNR", min = 13, max = 19} # This is a guess.
    juniors_20_23 = {name = "JNR", min = 20, max = 23}
    masters_40_44 = {name = "M1", min = 40, max = 44}
    masters_45_49 = {name = "M2", min = 45, max = 49}
    masters_50_54 = {name = "M3", min = 50, max = 54}
    masters_55_59 = {name = "M4", min = 55, max = 59}
    masters_60_64 = {name = "M5", min = 60, max = 64}
    masters_65_69 = {name = "M6", min = 65, max = 69}
    masters_70_74 = {name = "M7", min = 70, max = 74}
    masters_75_79 = {name = "M8", min = 75, max = 79}
    masters_80_84 = {name = "M9", min = 80, max = 84}
    masters_80p = {name = "M10", min = 80, max = 999}
    guest = {name = "Guest", min = 0, max = 999}

    # some results contain more typical IPL divisions
    o = {name = "Open", min = 0, max = 999}
    j13_15 = {name = "J13-15", min = 13, max = 15}
    j16_17 = {name = "J16-17", min = 16, max = 17}
    j18_19 = {name = "J18-19", min = 18, max = 19}

    m_40_44 = {name = "M40-44", min = 40, max = 44}
    m_45_49 = {name = "M45-49", min = 45, max = 49}
    m_50_54 = {name = "M50-54", min = 50, max = 54}
    m_55_59 = {name = "M55-59", min = 55, max = 59}
    m_60_64 = {name = "M60-64", min = 60, max = 64}
    m_65_69 = {name = "M65-69", min = 65, max = 69}
    m_70_74 = {name = "M70-74", min = 70, max = 74}
    m_75_79 = {name = "M75-79", min = 75, max = 79}
    m_80p = {name = "M80+", min = 80, max = 999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
