[divisions]
    open = {name = "Open", min=0, max=999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-12-31"]
    sex = "M"

[exemptions]
    6601 = ["ExemptDivision"] # Middle & Heavy
