# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
    when: never
  - if: "$CI_COMMIT_MESSAGE =~ /(WIP:|\\[nobuild\\]|\\[noci\\])/"
    when: never
  - if: "$CI_MERGE_REQUEST_TITLE =~ /(WIP:|\\[nobuild\\]|\\[noci\\])/"
    when: never
  - when: always
image: rust:slim-buster
meet-data:
  before_script:
  - apt-get update -qq && apt-get install -y python3-pip
  - pip3 install flake8
  script:
  - make check
pages:
  stage: deploy
  image: rust:latest
  variables:
    CARGO_HOME: "$CI_PROJECT_DIR/cargo"
  cache:
    key: mdbook-cache-key
    paths:
    - "$CARGO_HOME/bin"
  before_script:
  - export PATH="$PATH:$CARGO_HOME/bin"
  - mdbook --version || cargo install mdbook
  script:
  - mdbook build --dest-dir ../public book
  artifacts:
    paths:
    - public
  only:
  - main
include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
