language: python
python:
  - "3.6"

install:
  - pip3 install toml flake8

script: make check
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: PqlF4iF7jVWwCxFtkbzMLw9CNx1Xe6VyB5EWmvJa+FwWDRTpWv6qxMKbtpGkAVLwGfhiU1BiIpS4rumTSsmRL2Fs8JRnj66wqNK+LQghBE6OyLqnxZZOHRQNrqCLYRiKgDQMDWYzmeaPPo2M6TBdf6La8N1IXPL1QOT5Pb6cS2DWvSDtiHs1nBKlWnSmaHOmoktMZfGxiFDjr0I65JnZnBNqy15neegj6sQql89FGVtmyp75fMNeJKgw/a57LfGgiCUYl7oXQSCYwDZbl2BbxvgRXl3MHG3ZtpFact3kxA5stz6d4kTKAbEzTHIl0VZcCniim8eNGtie1TCqSy8U2JSeGXa+v0qsT0TSfX+F5xQNJmT4qkdJxJ0a3DRfzyHm/jN+pp5mE+uZGyq+7sl9ohztgQLQaE8DsJSux3i3DS9G0l8OH9od8DyBPWeuvlPm/dXbekgP2h/WdFun9WEee0zL8jp12gCO/JUQvsWWHSbmqTxV8dyljviu6uBEIFW0IqSOJ39J9LXQvByujpWq0UQFCJTX0vDXSbSmM47ULsXOz0c53mepoiQ7CAht41ixp/0Orxx+C3oDIBS+zb9OWI1dkt4PfwDvgLzg07oKETYgJzPPbfu4zRttzgAt+MOZnkdyhdS+zc8jte/7czBMlAw9/A+miHN5PzxqEV2XEew=
    on_success: change
    on_failure: always
