[workspace]
members = [
    "server",
]

# Give profiles higher optimization levels to avoid extreme CSV load times.
[profile.dev]
opt-level = 2

[profile.test]
opt-level = 2

[profile.release]
opt-level = 3
lto = true
