# Configuration for FCP

[options]
    require_manual_disambiguation = true

[divisions]
    
    mc = {name ="M-CL-PL",min=0,max=999,equipment="Raw",sex="M"}
    fc = {name ="F-CL-PL",min=0,max=999,equipment="Raw",sex="F"}
    
[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","69","76","84","84+"]
    date_range=["2021-01-01","9999-12-31"]
    sex = "F"

[exemptions]
