[divisions]
    unknown = {name='',min=14,max=18}
    9 = {name="9", min=14, max=15}
    10 = {name="10", min=15, max=16}
    11 = {name="11", min=16, max=17}
    12 = {name="12", min=17, max=18}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100", "100+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
