# Configuration for IHSPA.

[divisions]
    # The main division used for almost everything.
    men = {name="Men",min=0,max=999}
	women = {name="Women",min=0,max=999}
	menopen = {name="Men Open",min=0,max=999}
	womenopen = {name="Women Open",min=0,max=999}



[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
