# Configuration for WPC-RUS
[options]
    require_manual_disambiguation = true


[divisions]
    am_open = {name = "Amateur Open", min = 0, max = 999,tested="Yes"}
    am_youth = {name = "Amateur Youth", min = 5, max = 12,tested="Yes"}
    am_teen_13_14 = {name = "Amateur Teen 13-14", min = 13, max = 14,tested="Yes"}
    am_teen_15_19 = {name = "Amateur Teen 15-19", min = 15, max = 19,tested="Yes"}
    am_juniors_20_23 = {name = "Amateur Juniors 20-23", min = 20, max = 23,tested="Yes"}
    am_submasters_33_39 = {name = "Amateur Submasters 33-39", min = 33, max = 39,tested="Yes"}
    am_masters_40_44 = {name = "Amateur Masters 40-44", min = 40, max = 44,tested="Yes"}
    am_masters_45_49 = {name = "Amateur Masters 45-49", min = 45, max = 49,tested="Yes"}
    am_masters_50_54 = {name = "Amateur Masters 50-54", min = 50, max = 54,tested="Yes"}
    am_masters_55_59 = {name = "Amateur Masters 55-59", min = 55, max = 59,tested="Yes"}
    am_masters_60_64 = {name = "Amateur Masters 60-64", min = 60, max = 64,tested="Yes"}
    am_masters_65_69 = {name = "Amateur Masters 65-69", min = 65, max = 69,tested="Yes"}
    am_masters_70_74 = {name = "Amateur Masters 70-74", min = 70, max = 74,tested="Yes"}
    am_masters_75_79 = {name = "Amateur Masters 75-79", min = 75, max = 79,tested="Yes"}
    am_masters_80_84 = {name = "Amateur Masters 80-84", min = 80, max = 84,tested="Yes"}
    am_masters_80p = {name = "Amateur Masters 80+", min = 80, max = 999,tested="Yes"}

    pro_open = {name = "Pro Open", min = 0, max = 999}
    pro_youth = {name = "Pro Youth", min = 5, max = 12}
    pro_teen_13_14 = {name = "Pro Teen 13-14", min = 13, max = 14}
    pro_teen_15_19 = {name = "Pro Teen 15-19", min = 15, max = 19}
    pro_juniors_20_23 = {name = "Pro Juniors 20-23", min = 20, max = 23}
    pro_submasters_33_39 = {name = "Pro Submasters 33-39", min = 33, max = 39}
    pro_masters_40_44 = {name = "Pro Masters 40-44", min = 40, max = 44}
    pro_masters_45_49 = {name = "Pro Masters 45-49", min = 45, max = 49}
    pro_masters_50_54 = {name = "Pro Masters 50-54", min = 50, max = 54}
    pro_masters_55_59 = {name = "Pro Masters 55-59", min = 55, max = 59}
    pro_masters_60_64 = {name = "Pro Masters 60-64", min = 60, max = 64}
    pro_masters_65_69 = {name = "Pro Masters 65-69", min = 65, max = 69}
    pro_masters_70_74 = {name = "Pro Masters 70-74", min = 70, max = 74}
    pro_masters_75_79 = {name = "Pro Masters 75-79", min = 75, max = 79}
    pro_masters_80_84 = {name = "Pro Masters 80-84", min = 80, max = 84}
    pro_masters_80p = {name = "Pro Masters 80+", min = 80, max = 999}

    elite_pro_open = {name = "Elite Pro Open", min = 0, max = 999}

[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1980-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1980-01-01", "9999-01-01"]
    sex = "F"

[exemptions]