[divisions]
    m_o = {name = "M-O", min=0, max=999}
    m_t = {name = "M-T", min=14, max=16}
    m_sj = {name = "M-SJ", min=17, max=19}
    m_j = {name = "M-J", min=20, max=23}
    m_m1 = {name = "M-M1", min=40, max=49}
    m_m2 = {name = "M-M2", min=50, max=59}
    m_m3 = {name = "M-M3", min=60, max=69}
    m_m4 = {name = "M-M4", min=70, max=999}

    f_o = {name = "F-O", min=0, max=999}
    f_t = {name = "F-T", min=14, max=16}
    f_sj = {name = "F-SJ", min=17, max=19}
    f_j = {name = "F-J", min=20, max=23}
    f_m1 = {name = "F-M1", min=40, max=49}
    f_m2 = {name = "F-M2", min=50, max=59}
    f_m3 = {name = "F-M3", min=60, max=999}

[weightclasses.M]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["0000-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
