[divisions]
    open = {name ="Open",min=0,max=999}
    jun = {name ="Junior",min=20,max=23}
    master = {name ="Master",min=40,max=49} 
    teen = {name ="Teen",min=13,max=19} 
       
    tn1315 = {name ="Teen 13-15",min=13,max=15} 
    tn1617 = {name ="Teen 16-17",min=16,max=17} 
    tn1819 = {name ="Teen 18-19",min=18,max=19} 

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","145","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
