[divisions]


[weightclasses]


[exemptions]
    2302 = ["ExemptWeightClassConsistency"] # Women had no weightclasses.
    2303 = ["ExemptWeightClassConsistency"] # Non traditional weightclasses used.