# Configuration for the UPO.

[divisions]
    open = {name = "O", min = 0, max = 999}
    youth = {name = "Y", min = 0, max = 12} #Not an official division
    t_13_15 = {name = "T1", min = 13, max = 15}
    t_16_17 = {name = "T2", min = 16, max = 17}
    t_18_19 = {name = "T3", min = 18, max = 19}
    juniors = {name = "J", min = 20, max = 23}
    submasters = {name = "SM", min = 35, max = 39}
    m_40_44 = {name = "M1", min = 40, max = 44}
    m_45_49 = {name = "M2", min = 45, max = 49}
    m_50_54 = {name = "M3", min = 50, max = 54}
    m_55_59 = {name = "M4", min = 55, max = 59}
    m_60_64 = {name = "M5", min = 60, max = 64}
    m_65_69 = {name = "M6", min = 65, max = 69}
    m_70_74 = {name = "M7", min = 70, max = 74}
    m_75_79 = {name = "M8", min = 75, max = 79}
    m_80p = {name = "M9", min = 80, max = 999}
    m = {name = "M", min = 40, max = 999}

    pfm = {name = "PFM", min = 0, max = 999}

[weightclasses.default_M]
    classes = ["52", "56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44", "48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
    0801 =["ExemptWeightClassConsistency"] # No weightclasses
    0805 =["ExemptWeightClassConsistency"] # Reduced weightclasses
    0905 =["ExemptWeightClassConsistency"] # Reduced weightclasses
    1005 =["ExemptWeightClassConsistency"] # Reduced weightclasses
    1106 =["ExemptWeightClassConsistency"] # Reduced weightclasses