# Configuration for GFP

[divisions]
    open = {name ="O", min=0, max=999}
    youth = {name ="Y", min=5, max=12}
    juniors = {name ="J", min=20, max=23}
    teen = {name ="T", min=13, max=19}
    teen1 = {name ="T1", min=13, max=15}
    teen2 = {name ="T2", min=16, max=17}
    teen3 = {name ="T3", min=18, max=19}
    masters = {name ="M", min=40, max=999}
    masters1 = {name ="M1", min=40, max=49}
    masters2 = {name ="M2", min=50, max=59}
    masters3 = {name ="M3", min=60, max=69}
    masters4 = {name ="M4", min=70, max=79}
    masters5 = {name ="M5", min=80, max=89}

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-12-31"]
    sex = "F"

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["0000-01-01","9999-12-31"]
    sex = "M"

[exemptions]
    1901 = ["ExemptWeightClassConsistency"] #Weird weightclasses
    1902 = ["ExemptWeightClassConsistency"] #Weird weightclasses