[options]
    require_manual_disambiguation = true

[divisions]
    open = {name ="Open",min=0,max=999}
    blind = {name ="Blind",min=0,max=999}
    juniors = {name = "Juniors",min=0,max=22.5}
    subjuniors = {name = "Sub-Juniors",min=0,max=17.5}
    1318 = {name = "13-18",min=13,max=18}
    teen = {name = "Teen", min=13, max=19}
    masters1 = {name = "Masters 1",min=39.5,max=48.5}
    masters2 = {name = "Masters 2",min=49.5,max=58.5}
    masters3 = {name = "Masters 3",min=59.5,max=68.5}
    masters4 = {name = "Masters 4",min=69.5,max=999}
    paralympics = {name = "Paralympics",min=0,max=999}
    youth = {name = "Youth", min=5, max=16}

[weightclasses.default_M]
    classes = ["59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"

[weightclasses.subjunior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Sub-Juniors","13-18","Teen"]


[weightclasses.junior_M]
    classes = ["53","59","66","74","83","93","105","120","120+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"
    divisions = ["Juniors"]

[weightclasses.junior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Juniors"]

[weightclasses.subjunior_F]
    classes = ["43","47","52","57","63","72","84","84+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "F"
    divisions = ["Sub-Juniors","13-18","Teen"]

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_subjunior_M]
    classes = ["48","52","56","60","67.5","75","82.5","90","100","110","110+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"
    divisions = ["Sub-Juniors"]

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[weightclasses.old_subjunior_F]
    classes = ["40","44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"
    divisions = ["Sub-Juniors"]

[weightclasses.para_F]
    classes = ["40","44","48","52","56","60","67.5","75","82.5","82.5+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"
    divisions = ["Paralympics"]

[weightclasses.para_M]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","100+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"
    divisions = ["Paralympics"]

[exemptions]
    9001 = ["ExemptDivision"]
    0207 = ["ExemptWeightClassConsistency"]
    0310 = ["ExemptWeightClassConsistency"]
    0804 = ["ExemptWeightClassConsistency"]
    0805 = ["ExemptWeightClassConsistency"]
    0807 = ["ExemptWeightClassConsistency"]
    0808 = ["ExemptWeightClassConsistency"]
    0811 = ["ExemptWeightClassConsistency"]
    0812 = ["ExemptWeightClassConsistency"]
    0901 = ["ExemptWeightClassConsistency"]
    0903 = ["ExemptWeightClassConsistency"]
    0910 = ["ExemptWeightClassConsistency"]
    0911 = ["ExemptWeightClassConsistency"]
    1001 = ["ExemptWeightClassConsistency"]
    1002 = ["ExemptWeightClassConsistency"]
    1005 = ["ExemptWeightClassConsistency"] #Fewer weight classes
    1106 = ["ExemptWeightClassConsistency"]
    1107 = ["ExemptWeightClassConsistency"]
    1203 = ["ExemptWeightClassConsistency"]
    1301 = ["ExemptWeightClassConsistency"]
    1302 = ["ExemptWeightClassConsistency"]
    1303 = ["ExemptWeightClassConsistency"]
    1304 = ["ExemptWeightClassConsistency"]
    1306 = ["ExemptWeightClassConsistency"]
    1307 = ["ExemptWeightClassConsistency"]
    1309 = ["ExemptWeightClassConsistency"]
    1310 = ["ExemptWeightClassConsistency"]
    1313 = ["ExemptWeightClassConsistency"] # Youth Classes
    1314 = ["ExemptWeightClassConsistency"] # Youth Classes
    1403 = ["ExemptWeightClassConsistency"]
    1406 = ["ExemptWeightClassConsistency"]
    1408 = ["ExemptWeightClassConsistency"]
    1411 = ["ExemptWeightClassConsistency"]
    1417 = ["ExemptWeightClassConsistency"]
    1505 = ["ExemptWeightClassConsistency"]
    1509 = ["ExemptWeightClassConsistency"]
    1510 = ["ExemptWeightClassConsistency"]
    1607 = ["ExemptWeightClassConsistency"]
    1705 = ["ExemptWeightClassConsistency"]
    1804 = ["ExemptWeightClassConsistency"]
    1922 = ["ExemptWeightClassConsistency"]
    1919 = ["ExemptWeightClassConsistency"]
    1924 = ["ExemptWeightClassConsistency"]
    1937 = ["ExemptWeightClassConsistency"]
    1956 = ["ExemptWeightClassConsistency"]
    1961 = ["ExemptWeightClassConsistency"] #Masters have no weight class
    1962 = ["ExemptWeightClassConsistency"] #Masters have no weight class
    1813 = ["ExemptWeightClassConsistency"] #53s in Open
