[divisions]
    open = {name ="Open",min=0,max=999}
    submasters = {name ="Submasters 33-39",min=33,max=39}
    teen1315 = {name ="Teen 13-15",min=13,max=15}
    teen1617 = {name ="Teen 16-17",min=16,max=17}
    teen1819 = {name ="Teen 18-19",min=18,max=19}
    juniors2023 = {name ="Juniors 20-23",min=20,max=23}
    masters = {name ="Masters",min=40,max=999}
    masters1 = {name ="Masters 40-44",min=40,max=44}
    masters2 = {name ="Masters 45-49",min=45,max=49}
    masters3 = {name ="Masters 50-54",min=50,max=54}
    masters4 = {name ="Masters 55-59",min=55,max=59}
    masters5 = {name ="Masters 60-64",min=60,max=64}
    masters6 = {name ="Masters 65-69",min=65,max=69}
    masters7 = {name ="Masters 70-74",min=70,max=74}
    masters8 = {name ="Masters 75-79",min=75,max=79}
    masters9 = {name ="Masters 80-84",min=80,max=999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
    0501 = ["ExemptWeightClassConsistency"] # Lifters with no BW or WC.
