[divisions]
    open = {name ="Open",min=0,max=999,equipment="Raw"}
    juniors = {name = "Juniors",min=0,max=23,equipment="Raw"}
    teen = {name = "Teen",min=0,max=19,equipment="Raw"}
    masters1 = {name = "Masters 1",min=39,max=49,equipment="Raw"}
    masters2 = {name = "Masters 2",min=49,max=59,equipment="Raw"}
    masters3 = {name = "Masters 3",min=59,max=69,equipment="Raw"}
    masters4 = {name = "Masters 4",min=64,max=79,equipment="Raw"}
    masters5 = {name = "Masters 5",min=69,max=89,equipment="Raw"}

[weightclasses.default_M]
    classes = ["75","95","115","115+"]
    date_range = ["0000-01-01", "9999-01-01"]
    sex = "M"


[exemptions]
    1101 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1201 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1301 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses
    1302 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1303 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1401 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses
    1402 = ["ExemptWeightClassConsistency"]  # Women don't have a weightclass.
    1701 = ["ExemptWeightClassConsistency"]  # Didn't use weightclasses
