# Configuration for World Powerlifting.
# https://cdn.worldpowerlifting.com/wp-content/uploads/2019/07/world-powerlifting-rules.pdf

[divisions]
    # Over 14 years on the day of competition (assuming they meant >=).
    open = {name="Open", min=14, max=999}

    juniors = {name = "Juniors",min=0,max=22.5}
    subjuniors = {name = "Sub-Juniors",min=0,max=17.5}
  

    # Masters classes are entirely Birth-Year based.
    masters1 = {name="Masters 1", min=39.5, max=48.5}
    masters2 = {name="Masters 2", min=49.5, max=58.5}
    masters3 = {name="Masters 3", min=59.5, max=68.5}
    masters4 = {name="Masters 4", min=69.5, max=999}
    
[weightclasses.default_M]
    classes = ["62", "69", "77", "85", "94", "105", "120", "120+"]
    date_range = ["2018-08-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["48", "53", "58", "64", "72", "84", "100", "100+"]
    date_range = ["2018-08-01", "9999-01-01"]
    sex = "F"

[weightclasses.WP_juniorM]
    classes = ["56","62","69","77","85","94","105","120","120+"]
    date_range=["2018-08-25","9999-01-01"]
    sex = "M"
    divisions = ["Juniors","Sub-Juniors"]

[weightclasses.WP_juniorF]
    classes = ["44", "48", "53", "58", "64", "72", "84", "100", "100+"]
    date_range=["2018-08-25","9999-01-01"]
    sex = "F"
    divisions = ["Juniors","Sub-Juniors"]

[exemptions]
    2202 = ["ExemptWeightClassConsistency"]
