[divisions]
# Intentionally left blank.

[weightclasses]
# Intentionally left blank.

[exemptions]
IP-2002-01-16-C = ["ExemptDuplicates"] # With IP-2002-01-17-A.
IP-2002-01-17-A = ["ExemptDuplicates"] # With IP-2002-01-16-C.
IP-2002-02-16-B = ["ExemptDuplicates"] # With IP-2002-02-16-C.
IP-2002-02-16-C = ["ExemptDuplicates"] # With IP-2002-02-16-B.
