[divisions]
    mor = {name ="M-OR",min=0,max=999}
 
[weightclasses.default_M]
    classes = ["56","60","67.5","75","82.5","90","100","110","125","140","125+","140+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90+"]
    date_range = ["2016-01-01","9999-01-01"]
    sex = "F"

[exemptions]
