[divisions]
    1A2A = {name="1A-2A", min=13, max=19}
    1A = {name="1A", min=13, max=19, sex="M"}
    2A = {name="2A", min=13, max=19, sex="M"}
    3A = {name="3A", min=13, max=19, sex="M"}
    4A = {name="4A", min=13, max=19, sex="M"}
    5A = {name="5A", min=13, max=19, sex="M"}
    6A = {name="6A", min=13, max=19, sex="M"}
    class1 = {name="Class I", min=13, max=19, sex="F"}
    class2 = {name="Class II", min=13, max=19, sex="F"}
    class3 = {name="Class III", min=13, max=19, sex="F"}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range=["2002-01-01","9999-01-01"]
    sex = "M"

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range=["0000-01-01","2001-12-31"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44.5","48","52","56","60","67.5","75","82.5","90","100", "110", "110+"]
    date_range=["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
        #State and North/South meets let you be 4 and 2 pounds over respectively, making the weight classes overlap
	2101 = ["ExemptWeightClassConsistency"]
