# Configuration for the UgandaPA.

[options]
    require_manual_disambiguation = true

[rulesets.default]
    ruleset = ["CombineRawAndWraps"]
    date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    open = {name ="Open",min=0,max=999}

    masters4044 = {name ="M40-44",min=40,max=44} 
    masters4549 = {name ="M45-49",min=45,max=49} 
    masters5054 = {name ="M50-54",min=50,max=54} 
    masters5459 = {name ="M55-59",min=55,max=59} 
    masters6064 = {name ="M60-64",min=60,max=64} 
    masters6569 = {name ="M65-69",min=65,max=69} 
    masters7074 = {name ="M70-74",min=70,max=74} 
    masters7579 = {name ="M75-79",min=75,max=79} 
    masters80 = {name ="M80+",min=80,max=999}
    teen1315 = {name ="T13-15",min=13,max=15} #Teen 1
    teen1617 = {name ="T16-17",min=16,max=17} #Teen 2
    teen1819 = {name ="T18-19",min=18,max=19} #Teen 3
  
    j20_23 = {name="J20-23", min=20, max=23}
    s35-39 = {name="S35-39", min=35, max=39}
    paralymic_j20_23 = {name="Paralympic J20-23", min=20, max=23}
    paralympic_m40p = {name="Paralympic M40+", min=40, max=999}

[weightclasses.default_M]
    classes = ["39","44","48","52","56","60","67.5","75","82.5","90","100","110","125","140","155","125+","140+","155+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["39","44","48","52","56","60","67.5","75","82.5","90","100","90+","100+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]
