[divisions]
    open = {name = "Open", min = 0, max = 999}
    youth_under_6 = {name = "Youth Under 6", min = 0, max = 5}
    youth6_7 = {name = "Youth 6-7", min = 6, max = 7}
    youth8_9 = {name = "Youth 8-9", min = 8, max = 9}
    youth10_11 = {name = "Youth 10-11", min = 10, max = 11}
    teen_12_13 = {name = "Teen 12-13", min = 12, max = 13}
    teen_14_15 = {name = "Teen 14-15", min = 14, max = 15}
    teen_16_17 = {name = "Teen 16-17", min = 16, max = 17}
    teen_18_19 = {name = "Teen 18-19", min = 18, max = 19}
    teen_20_23 = {name = "Juniors 20-23", min = 20, max = 23}
    submasters = {name = "Sub-Masters 35-39", min = 35, max = 39}
    masters_40_44 = {name = "Masters 40-44", min = 40, max = 44}
    masters_45_49 = {name = "Masters 45-49", min = 45, max = 49}
    masters_50_54 = {name = "Masters 50-54", min = 50, max = 54}
    masters_55_59 = {name = "Masters 55-59", min = 55, max = 59}
    masters_60_64 = {name = "Masters 60-64", min = 60, max = 64}
    masters_65_69 = {name = "Masters 65-69", min = 65, max = 69}
    masters_70_74 = {name = "Masters 70-74", min = 70, max = 74}
    masters_75_79 = {name = "Masters 75-79", min = 75, max = 79}
    masters_80_84 = {name = "Masters 80-84", min = 80, max = 84}


    special_olympics = {name = "Special Olympics", min = 0, max = 999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","145","145+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[weightclasses.youth_M]
    classes = ["30","35","40","44","48","52","56","60","67.5","75","82.5","90","100","110","125","145","145+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"
    divisions = ["Youth Under 6","Youth 6-7","Youth 8-9","Youth 10-11","Teen 12-13"]

[weightclasses.youth_F]
    classes = ["30","35","40","44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"
    divisions = ["Youth Under 6","Youth 6-7","Youth 8-9","Youth 10-11","Teen 12-13"]

[exemptions]
    0401 = ["ExemptWeightClassConsistency"] # Men in lower weightclasses
    1201 = ["ExemptDivision","ExemptWeightClassConsistency"] #Juniors 20-24, 140+