[options]
    require_manual_disambiguation = true

[divisions]
    open = {name ="Open",min=0,max=999}
    junior = {name = "JR",min=19,max=23}
    subjunior = {name = "SJR",min=0,max=18}
    masters1 = {name = "M1",min=40,max=49}
    masters2 = {name = "M2",min=50,max=59}
    masters3 = {name = "M3",min=60,max=69}
    masters4 = {name = "M4",min=70,max=999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range=["2021-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100","100+"]
    date_range=["2021-01-01","9999-01-01"]
    sex = "F"


[exemptions]
