# Configuration for BAWLA
[options]
    require_manual_disambiguation = true


[divisions]
#Intentionally blank  

[weightclasses]
#Intentionally blank  

[exemptions]
0814 = ["ExemptDuplicates"] # With epa/0808.
