#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Simple script to run over a list of names and output any
# that are listed as being both M and F.
#
import sys
import os

try:
    import oplcsv
except ModuleNotFoundError:
    sys.path.append(os.path.join(os.path.dirname(
        os.path.dirname(os.path.realpath(__file__))), "scripts"))
    import oplcsv
import re


# Hashtable for sex lookup.
# str -> [int, int] (left for male, right for female).
NameToSexHash = {}

###############################################

errorCount = 0
warningCount = 0


def redden(s):
    if os.name != 'nt':
        return "\033[1;31m" + s + "\033[0;m"
    return s


def enyellow(s):
    if os.name != 'nt':
        return "\033[1;33m" + s + "\033[0;m"
    return s


def perror(s):
    global errorCount
    errorCount += 1
    print(' ' + redden(s), file=sys.stderr)


def pwarning(s):
    global warningCount
    warningCount += 1
    print(' ' + enyellow(s), file=sys.stderr)

###############################################


def cleanup(filename):

    csv = oplcsv.Csv(filename)


    sexidx = csv.index('Sex')
    
    if 'BodyweightKg' in csv.fieldnames:
        bwidx = csv.index('BodyweightKg')
    wcidx = csv.index('WeightClassKg')

    if 'Division' in csv.fieldnames:
        dividx = csv.index('Division')


 
    for row in csv.rows:
        sex = row[sexidx]

        if sex == 'F' and 'BodyweightKg' in csv.fieldnames:
            bw = row[bwidx]
            if bw != '':
                bw = float(bw)
                if bw > 90 and bw <= 100:
                    row[wcidx] = '100'
                elif bw > 100 and bw <= 110:
                    row[wcidx] = '110'
                elif bw > 110:
                    row[wcidx] = '110+' 


        if 'Division' in csv.fieldnames:
            if row[dividx] == 'Pro Police/Fire/Military Open':
                row[dividx] = 'Police/Fire/Military Pro Open'
            elif 'Police-Fire' in row[dividx]:
                row[dividx] = row[dividx].replace('Police-Fire','Police/Fire/Military') 
        with open(filename, 'w') as fd:
            csv.write(fd)



def main():
    for dirname, subdirs, files in os.walk(os.getcwd()):
        if 'entries.csv' in files:
            entriespath = dirname + os.sep + 'entries.csv'
            cleanup(entriespath)



if __name__ == '__main__':
    sys.exit(main())
