[divisions]
    open = {name = "Open", min=0, max=999}
    juniors = {name = "Juniors", min=0, max=22.5}
    youth = {name = "Youth", min=14, max=18}
    masters1 = {name = "Masters 1", min=39.5, max=999}
    masters2 = {name = "Masters 2", min=49.5, max=999}
    masters3 = {name = "Masters 3", min=59.5, max=999}
    masters4 = {name = "Masters 4", min=69.5, max=999}
    masters5 = {name = "Masters 5", min=79.5, max=999}

[weightclasses.old_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","125+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","2010-12-31"]
    sex = "F"

[exemptions]
    8701 = ["ExemptWeightClassConsistency"] # No weightclasses.
