#!/usr/bin/env python3

import oplcsv
import sys

def main(filename):
    csv = oplcsv.Csv(filename)


    nameidx = csv.index('Name')
    benchidx = csv.index('Best3BenchKg')
    bench4idx = csv.index('Bench4Kg')
    deadidx = csv.index('Best3DeadliftKg')
    dead4idx = csv.index('Deadlift4Kg')
    eventidx = csv.index('Event')

    row_copy = csv.rows

    # Get a list of all the rows in this category that placed.
    for row in csv.rows:
        if row[eventidx] == 'BD':
            for row2 in row_copy:
                if row[nameidx] == row2[nameidx] and row2[eventidx] == 'B':
                    row[benchidx] = row2[benchidx]
                    if row[bench4idx] == '':
                        row[bench4idx] = row2[bench4idx]
                    break
    for row in csv.rows:
        if row[eventidx] == 'BD':
            for row2 in row_copy:
                if row[nameidx] == row2[nameidx] and row2[eventidx] == 'D':
                    row[deadidx] = row2[deadidx]    
                    if row[dead4idx] == '':
                        row[dead4idx] = row2[dead4idx] 


    with open(filename, 'w') as fd:
        csv.write(fd)


if __name__ == '__main__':
    main('entries.csv')
