[divisions]
    open = {name ="Open",min=0,max=999}
    disabled = {name ="Disabled",min=0,max=999}
    infantil = {name ="Infantil",min=0,max=16}
    juvenil1 = {name ="Juvenil 1",min=17,max=19}
    juvenil2 = {name ="Juvenil 2",min=20,max=23}
    master1 = {name ="Masters 1",min=40,max=49}
    master2 = {name ="Masters 2",min=50,max=59}


[weightclasses.M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","110+","140+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "M"

[weightclasses.F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["0000-01-01","9999-01-01"]
    sex = "F"

[exemptions]