# Configuration for Insanity.

[divisions]
    open = {name="Open", min=0, max=999}

    frauen = {name="Frauen", min=0, max=999} # Women
    herren = {name="Herren", min=0, max=999} # Men
 
[weightclasses.default_M]
    classes = ["75", "90", "105", "105+"]
    date_range=["0000-01-01", "9999-01-01"]
    sex = "M"

[exemptions]
    1501 = ["ExemptWeightClassConsistency"]
    1601 = ["ExemptWeightClassConsistency"]
    1701 = ["ExemptWeightClassConsistency"]
    1801 = ["ExemptWeightClassConsistency"]
    1901 = ["ExemptWeightClassConsistency"]
