[divisions]
    # Age in 100% RAW is determined by exact age on date of meet.
    open = {name = "Open", min = 0, max = 999}
    kids_6 = {name = "Kids", min = 6, max = 7}
    kids_8 = {name = "Kids", min = 8, max = 9}
    kids_10 = {name = "Kids", min = 10, max = 11}
    youth = {name = "Youth", min = 12, max = 13}
    teen_14 = {name = "Teen", min = 14, max = 15}
    teen_16 = {name = "Teen", min = 16, max = 17}
    teen_18 = {name = "Teen", min = 18, max = 19}
    junior = {name = "Junior", min = 20, max = 23}
    submaster = {name = "Sub-master", min = 35, max = 39}
    master_40 = {name = "Master", min = 40, max = 44}
    master_45 = {name = "Master", min = 45, max = 49}
    master_50 = {name = "Master", min = 50, max = 54}
    master_55 = {name = "Master", min = 55, max = 59}
    master_60 = {name = "Master", min = 60, max = 64}
    master_65 = {name = "Master", min = 65, max = 69}
    master_70 = {name = "Master", min = 70, max = 74}
    master_75 = {name = "Master", min = 75, max = 79}
    master_80 = {name = "Master", min = 80, max = 999}
    special = {name = "Special Olympian", min = 0, max = 999}
    novice = {name = "Novice", min = 0, max = 999}

[weightclasses.current_M]
    classes = ["44", "48","52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["2013-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.current_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","100", "100+"]
    date_range = ["2013-01-01", "9999-01-01"]
    sex = "F"

