#!/usr/bin/env python3
# vim: set ts=8 sts=4 et sw=4 tw=99:
#
# Probes for new Fédération Française de Force meets.

from bs4 import BeautifulSoup
import os
import sys
import requests

try:
    import oplprobe
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(os.path.dirname(
        os.path.dirname(os.path.realpath(__file__)))), "scripts"))
    import oplprobe


RESULTS_URL = "https://www.ffforce.fr/fr/nos-disciplines/force-athletique-ffforce/competitions-force-athletique/archives-des-resultats-force-athletique.html"
FEDDIR = os.path.dirname(os.path.realpath(__file__))


def color(s):
    return "\033[1;37m" + s + "\033[0;m"


def getmeetlist(html):
    soup = BeautifulSoup(html, 'html.parser')

    # get the value attribute for the most recent season in the season dropdown then make a POST request
    season_selector = soup.find('select')
    options = season_selector.find_all('option')
    most_recent_season = options[1]['value']
    most_recent_results = requests.post(RESULTS_URL, {'jsArtSelectCategorie': most_recent_season})
    soup_most_recent_results = BeautifulSoup(most_recent_results.text, 'html.parser')

    main = soup_most_recent_results.find("div", {"class": "tableau-classmt"})
    assert main, "No <div> element with class `tableau-classmt` found."

    links = main.find_all("a")
    assert links, "No <a> elements found."

    return set(map(lambda link: "https://www.ffforce.fr" + link['href'].strip(), links))


def main():
    html_content = oplprobe.gethtml(RESULTS_URL)
    meets_list = getmeetlist(html_content)

    entered = oplprobe.getenteredurls(FEDDIR)
    unentered = oplprobe.getunenteredurls(meets_list, entered)

    oplprobe.print_meets(color('[FFForce]'), unentered)


if __name__ == '__main__':
    main()
